# Generated by Django 5.2.4 on 2025-07-19 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_invitation_created_by_invitation_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuelog',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues.issue'),
        ),
    ]
